services:
  postgres:
    image: postgres:15-alpine
    container_name: tms-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tmsdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tms-network

  zookeeper:
    image: arm64v8/zookeeper
    container_name: tms-zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    networks:
      - tms-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: tms-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - tms-network

  auth-service:
    build: ../auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - tms-network

  testcase-service:
    build: ../testcase-service
    container_name: testcase-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - kafka
    networks:
      - tms-network

  testrunner-service:
    build: ../testrunner-service
    container_name: testrunner-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - kafka
    networks:
      - tms-network

  report-service:
    build: ../report-service
    container_name: report-service
    ports:
      - "8084:8084"
    depends_on:
      - postgres
      - testcase-service
    networks:
      - tms-network

volumes:
  postgres_data:

networks:
  tms-network:
    driver: bridge